ktor:
    application:
        modules:
            - org.jetbrains.ApplicationKt.configure
            - org.jetbrains.ApplicationKt.module
    deployment:
        port: 8080
config:
    database:
        jdbcUrl: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
        username: "sa"
        password: ""
        flyway:
            locations: "$FLYWAY_LOCATIONS:db/migration"
            baselineOnMigrate: "$FLYWAY_BASELINE_ON_MIGRATE:true"
    auth:
      encryptionKey: "$AUTH_SESSION_CRYPT_KEY:b324d8a737c6cb016f2c1b6e3501ecb2"
      signKey: "$AUTH_SESSION_SIGN_KEY:59aa1b97d4baf65e1a95101aa35cff307fb9c9e653918f14e33736c2bd3362ca"
      clientId: "$AUTH_CLIENT_ID:<client-id>"
      clientSecret: "$AUTH_CLIENT_SECRET:<empty>"
    ai:
      apiKey: "$AI_API_KEY:<api-key>"
      model: "$AI_MODEL:gpt-4o-mini"
      maxSegmentSizeInTokens: "$AI_MAX_SEGMENT_SIZE:550"
      maxOverlapSizeInTokens: "$AI_MAX_OVERLAP_SIZE:50"