ktor:
    application:
        modules:
            - org.jetbrains.ApplicationKt.configure
            - org.jetbrains.ApplicationKt.module
    deployment:
        port: 8080
config:
  database:
    jdbcUrl: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: ""
    flyway:
      locations: "$FLYWAY_LOCATIONS:db/migration"
      baselineOnMigrate: "$FLYWAY_BASELINE_ON_MIGRATE:true"
