ktor:
    application:
        modules:
            - org.jetbrains.ApplicationKt.configure
            - org.jetbrains.ApplicationKt.module
    deployment:
      port: "$PORT:8080"
config:
    database:
        username: "sa"
        password: ""
        flyway:
            locations: "$FLYWAY_LOCATIONS:classpath:db/migration"
            baselineOnMigrate: "$FLYWAY_BASELINE_ON_MIGRATE:true"
